### ISSUE TITLE
Remove handlebars dependency

### ISSUE THREAD

**Issue by tricknotes** [emberjs/ember-rails#444]
It should be depended from Ember.js (< 1.9) or template compiler.

## Road map
* [x] Update generator -> https://github.com/emberjs/ember-rails/pull/451
* [x]  Remove handlebars dependency from barber -> https://github.com/tchak/barber/pull/35
* [x] Remove handlebars dependency from ember-rails -> https://github.com/emberjs/ember-rails/pull/452

**Comment by tricknotes** [comment]
First, It is required that barber independent from handlebars-source.
ref: https://github.com/tchak/barber/pull/35

**Comment by tricknotes** [comment]
I updated this PR's description with road map.

**Comment by tricknotes** [comment]
done for all PRs are merged.
